export const [RADIANT, DIRE] = ['team2', 'team3'];
export const [
  GS_INIT,
  GS_WAIT,
  GS_DRAFT,
  GS_STRAT,
  GS_SHOW,
  GS_PRE,
  GS_INGAME,
  GS_POST,
  GS_LAST,
  GS_DC,
] = [
  'DOTA_GAMERULES_STATE_INIT',
  'DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD',
  'DOTA_GAMERULES_STATE_HERO_SELECTION',
  'DOTA_GAMERULES_STATE_STRATEGY_TIME',
  'DOTA_GAMERULES_STATE_TEAM_SHOWCASE',
  'DOTA_GAMERULES_STATE_PRE_GAME',
  'DOTA_GAMERULES_STATE_GAME_IN_PROGRESS',
  'DOTA_GAMERULES_STATE_POST_GAME',
  'DOTA_GAMERULES_STATE_LAST',
  'DOTA_GAMERULES_STATE_DISCONNECT',
];
